language: generic 
sudo: required
services:
  - docker 

before_install:
  # - docker build -f Dockerfile.dev .
  - docker build -t abelregov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abelregov/docker-react yarn run test
  # - docker run -e CI=true USERNAME/docker-react yarn run test