# For PROD Deployment
FROM node:alpine as builder
WORKDIR '/app'
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn run build
 
FROM nginx
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html

# only if there's an error deploying
# COPY --from=0 /app/build /usr/share/nginx/html 
